### ISSUE TITLE
Issue with Value 0 in Table 2

### ISSUE THREAD

**Issue by tuexen** [sctplab/rfc4960bis#14] opened 2015-07-23 09:22 UTC
Table 2 of RFC4960 has value 0 of Peerís Tag in row with Action B while value 0 is explained in Legend as `No Tie-Tag in cookie (unknown)`.

13.2    Text Changes to the Document:

---
## Old text (Section 5.2.4):

Legend:
   X - Tag does not match the existing TCB.
   M - Tag matches the existing TCB.
   0 - No Tie-Tag in cookie (unknown).
   A - All cases, i.e., M, X, or 0.

---
## New text (Section 5.2.4):

Legend:
   X - Tag does not match the existing TCB.
   M - Tag matches the existing TCB.
   0 - No Tag in cookie (unknown).
   A - All cases, i.e., M, X, or 0.

13.3    Solution Description:

The NEW text uses `Tag` in the explanation of value 0 that refers to any Tag of the table (Local Tag, Peerís Tag, Local-Tie-Tag, Peerís-Tie-Tag).

Discuss via e-mail. Only a typo?

**Comment by MaximProshin** [comment] 2015-10-21 18:32
I have looked at this issue and this is my feedback.

It seems that the initialization use case when the peer’s VTag in the cookie is 0 is impossible and thus row (M,0,A,A) in Table 2 is useless.
So the issue is not just editorial.

Moreover note that the "SCTP Reference Guide" book, bullet 8 of Section 4.7.3.2 describes the “COOKIE ECHO in COOKIE_ECHOED state” use case and refers to row (M,0,A,A) in the table and the description seems to be not right. Namely, in bullet 4 EP A builds the cookie where it includes VT_peer=Z’ and sends it in INIT ACK. When INIT ACK is received by EP Z in bullet 6, it sends this cookie back in COOKIE ECHO. So when COOKIE ECHO is received in COOKIE_ECHOED state of EP A in bullet 8, the cookie includes VT_peer=Z’. In TCB VT_peer=Z. As a result, it matches row (M,X,A,A) of the table and thus still B) so actions are the same as in row (M,0,A,A). 

Perhaps it was mixed with the initialization collision case where the peer's VTag in TCB is not defined (=0) while there is the peer’s VTag in the received cookie. Such use case happens when COOKIE ECHO is received in COOKIE_WAIT state in the following scenario:
![image](https://cloud.githubusercontent.com/assets/13518722/10646291/0c03eb9c-783b-11e5-9e9f-599492cc621a.png)

If my thoughts right then I see two different ways how to handle the issue:
1.  remove row (M,0,A,A) in Table 2
2.  replace ‘0’ in the second column with ‘U’ or similar and explain the meaning (Peer’s Tag in the TCB is undefined)

**Comment by MaximProshin** [comment] 2015-10-22 08:23
it can be combined with issue #15 and then make changes in the following way:
3.  replace ‘0’ in the second column with ‘U’ or similar and replace B) by a new action B'') like proposed in issue #15

**Comment by MaximProshin** [comment] 2016-02-23 19:25
see proposed changes in #33

**Comment by tuexen** [comment] 2017-06-30 13:29
@MaximProshin If I remember it correctly, we discussed this and concluded that no change is required. Is that correct?

**Comment by MaximProshin** [comment] 2017-07-03 06:34
yes, we agreed to close it without any changes in the draft.

**Closed as completed by MaximProshin** 2017-07-03 06:34 UTC
Labels: Discuss in Prague

**Comment by Ralith** [comment] 2017-11-14 06:04
How exactly was this resolved? The table and related text remains confusing and apparently contradictory.

RFC4960 5.2.2 states:
> If no new addresses are added, when responding to the INIT in the outbound INIT ACK, the endpoint MUST copy its current Tie-Tags to a reserved place within the State Cookie and the association's TCB.  We shall refer to these locations inside the cookie as the Peer's-Tie-Tag and the Local-Tie-Tag.  We will refer to the copy within an association's TCB as the Local Tag and Peer's Tag.

which suggests that the only meaningful comparison that can be performed is between the tie-tags in the echoed cookie (the "Peer's-Tie-Tag" and "Local-Tie-Tag") and those in the TCB (the "Local Tag" and "Peer's Tag"), in which case it is unclear what an `M` or `X` in the table could possibly be comparing to.

The table seems to make more sense if, contrary to 5.2.2, the terms "Local Tag" and "Peer's Tag" are interpreted as describing the *verification* tags stored in the state cookie, to be compared to the verification tags stored in the TCB. However, in that case the definition of `0` as describing a tie-tag is inconsistent with its use in the second column, and I am unable to identify any occasion in which a state cookie would be transmitted with a zero for the peer's verification tag regardless.

This confusion is compounded by the mysterious treatment of tie tags in the RFC4960 text at large:
- The naming and the presence of two distinct values instead of a single nonce suggests that each value has a semantic relationship to one of the two communicating endpoints, but the definition given in 1.3 suggests that there is this is not so, and provides no insight into why a simple nonce is split into two parts. I can speculate historical reasons, but no backwards compatibility threat is apparent from a terminology clarification, let alone one regarding data only exchanged in the state cookie.
- Neither 13.1 nor 13.2 make any clear mention of any tie tags, despite 1.3 suggesting that they reside in the TCB, and 5.2.2 suggesting that the endpoint stores them as well.
- 5.2.2 mentions the endpoint's "current Tie-Tags" as if they are subject to change, but it is unclear if or how tie-tags change over time. Given the goal of detecting restarts of a particular association, I have difficulty understanding why they would ever be shared between multiple associations on an endpoint, let alone held entirely constant.
- Figure 5 contradicts the definition given in 1.3 by assigning tie-tags the value of previous verification tags.

My best hypothesis is that the "tie-tags" should be a single 64-bit nonce, generated fresh and both stored in the TCB (not the endpoint) and transmitted in an INIT ACK state cookie whenever a duplicate INIT is received, so that the ensuing COOKIE ECHO can be identified and a restart notification ultimately produced. However, it is difficult to proceed with confidence when the RFC contradicts this in multiple locations and the procedure for handling a COOKIE ECHO when a TCB exists remains unclear.

Is it possible for this to be clarified?
